name: CI

on: [push, pull_request]

env:
  CI: true
  NODE_ENV: test
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}
    - uses: actions/cache@v1
      if: always()
      with:
        path: ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('packages/meriyah/package-lock.json') }}-${{ hashFiles('packages/wiz/package-lock.json') }}
    - name: "Test: meriyah"
      run: |
        set -e
        cd packages/meriyah
        npm install
        npm run build
        npm test
    - name: "Test: wiz"
      run: |
        set -e
        cd packages/wiz
        npm install
        npm run build
        npm test
    - name: Publish
      if: "startsWith(github.ref, 'refs/tags/v') && matrix.node == 8"
      run: |
        set -e
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
        cd packages/wiz
        npm publish
