name: CI

on: [push]

env:
  CI: true
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    - uses: actions/cache@v1
      with:
        path: ~/.cache
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
    - run: npm install
    - run: npm test
    - name: npm publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
        npm publish
